### ISSUE TITLE
Does not compile on Windows

### ISSUE THREAD

**Issue by logicmason** [asaaki/cmark.ex#28]
```D:\elixirstuff\markdown_project">mix deps.compile
==> cmark
could not compile dependency :cmark, "mix compile" failed. You can recompile this dependency with "mix deps.compile cmark", update it with "mix deps.update cmark" or clean it with "mix deps.clean cmark"
** (ErlangError) Erlang error: :enoent
    (elixir) lib/system.ex:605: System.cmd("make", [], [stderr_to_stdout: true])
```

**OS**: Win10
**c compilers installed**: VS 2015, clang 4.0
**shells tried**: git bash, powershell, Developer Command Prompt for VS2015 after running vcvarsall.bat
**other notes**: both Cmake and Nmake are installed, compiling bcrypt and other NIFs doesn't fail

**Comment by asaaki** [comment]
I have not a Windows machine for testing, but I suspect that it fails due to differences in the `make` implementations (I have never used nmake so far).

I'd probably need to check with other NIF project's build pipelines.
If you have some recommendations I might be able to adjust and fix it for you.
